-- AlterEnum
ALTER TYPE "TransactionType" ADD VALUE 'DIVIDEND';

-- AlterTable
ALTER TABLE "Holding" ADD COLUMN "fee" DECIMAL NOT NULL DEFAULT 0;
ALTER TABLE "Holding" ADD COLUMN "tax" DECIMAL NOT NULL DEFAULT 0;
